version: '3'

services:
  web:
    user: ${CURRENT_HOST_USER}
    build:
      context: .docker/php-fpm
    depends_on:
      - mysql
    volumes:
      - ./:/var/www

  nginx:
    user: ${CURRENT_HOST_USER}
    build:
      context: .docker/nginx
    volumes:
      - ./:/var/www
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.docker/nginx/sites/:/etc/nginx/sites-available
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./.docker/logs:/var/log
    depends_on:
      - web
    ports:
      - "8080:80"
      - "443:443"

  frontend:
    image: node:12.16.3
    user: node
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    command: bash -c "yarn && yarn encore dev --watch"

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./.docker/mysql-data:/var/lib/mysql
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=storage
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1234
    ports:
      - "3306:3306"
    expose:
      - '3306'
volumes:
    mysql:


